# Jekyll конфігурація для GitHub Pages
# Растрова та векторна графіка - навчальний курс

# Основні налаштування сайту
title: "Растрова та векторна графіка"
description: "Навчальний ресурс з інформатики для учнів 10-11 класів. Вивчення принципів побудови, властивостей та відмінностей між растровою та векторною графікою."
author: "Матвєєва Анна"
email: ""
baseurl: "" # Субшлях, якщо сайт не в корені (наприклад: /my-repo)
url: "" # URL сайту (GitHub Pages автоматично встановить)

# GitHub Pages налаштування
repository: "" # username/repository-name
github_username: ""

# Jekyll налаштування
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Включение файлов
include:
  - _pages
  - theory
  - practice  
  - tests
  - resources

# Исключения из обработки
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git/
  - .gitignore

# Налаштування Markdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Навігація
header_pages:
  - theory/main-content.md
  - practice/beginner-tasks.md
  - tests/basic-test.md
  - resources/glossary.md

# УБИРАЮ COLLECTIONS - используем обычные pages
# collections:
#   theory:
#     output: true
#     permalink: /:collection/:name/

# Налаштування SEO
seo:
  name: "Растрова та векторна графіка"
  type: "Course"
  author: "Матвєєва Анна"
  description: "Навчальний курс з інформатики для учнів 10-11 класів про растрову та векторну графіку"

# Соціальні мережі (опціонально)
social:
  - platform: github
    user_url: "https://github.com/"
  - platform: email
    user_url: "mailto:"

# Налаштування теми
minima:
  skin: classic
  social_links:
    github: ""
    
# Мова сайту
lang: uk

# Часовий пояс
timezone: Europe/Kiev

# Пагінація (якщо потрібна)
paginate: 10
paginate_path: "/page:num/"

# Налаштування дати
date_format: "%d.%m.%Y"

# Підтримка математичних формул (MathJax)
mathjax: true

# Налаштування для навчального контенту
course:
  name: "Растрова та векторна графіка"
  level: "10-11 класи"
  subject: "Інформатика"
  duration: "16 годин"
  ai_tools:
    - "Claude"
    - "ChatGPT"

# Власні змінні
custom:
  show_navigation: true
  enable_search: true
  enable_comments: false
  enable_analytics: false
